services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notesapp_php
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor   # ensure vendor is synced
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      APP_ENV=production
      APP_DEBUG=false
      DB_HOST=db
      DB_PORT=3306
      DB_DATABASE=notesapp
      DB_USERNAME=root
      DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: notesapp_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
